// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-Y5nS4hNd7VyI6msNe06BvEJb_p-w_c',
    appId: '1:464871223089:web:8d8e7b1f75c994b75a8a10',
    messagingSenderId: '464871223089',
    projectId: 'munasabat-2d9c2',
    authDomain: 'munasabat-2d9c2.firebaseapp.com',
    storageBucket: 'munasabat-2d9c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_O4pIHW2gB86LH0z_YD_puh80nV_xW5E',
    appId: '1:464871223089:android:bc79b81d2c53c0d05a8a10',
    messagingSenderId: '464871223089',
    projectId: 'munasabat-2d9c2',
    storageBucket: 'munasabat-2d9c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKtrYEkFWKqocFzwFpQ_rm9VThk5vCbWs',
    appId: '1:464871223089:ios:2b13e84631f6df8c5a8a10',
    messagingSenderId: '464871223089',
    projectId: 'munasabat-2d9c2',
    storageBucket: 'munasabat-2d9c2.firebasestorage.app',
    iosBundleId: 'com.example.munasabat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKtrYEkFWKqocFzwFpQ_rm9VThk5vCbWs',
    appId: '1:464871223089:ios:2b13e84631f6df8c5a8a10',
    messagingSenderId: '464871223089',
    projectId: 'munasabat-2d9c2',
    storageBucket: 'munasabat-2d9c2.firebasestorage.app',
    iosBundleId: 'com.example.munasabat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB-Y5nS4hNd7VyI6msNe06BvEJb_p-w_c',
    appId: '1:464871223089:web:edcec3a3bfc32bf75a8a10',
    messagingSenderId: '464871223089',
    projectId: 'munasabat-2d9c2',
    authDomain: 'munasabat-2d9c2.firebaseapp.com',
    storageBucket: 'munasabat-2d9c2.firebasestorage.app',
  );
}
