import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../core/services/stripe_service.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../../core/widgets/primary_button.dart';
import '../../models/gift_model.dart';
import '../../providers/auth_provider.dart';
import '../../repositories/gift_repository.dart';

class SendGiftScreen extends ConsumerStatefulWidget {
  final String eventId;

  const SendGiftScreen({super.key, required this.eventId});

  @override
  ConsumerState<SendGiftScreen> createState() => _SendGiftScreenState();
}

class _SendGiftScreenState extends ConsumerState<SendGiftScreen> {
  final _amountController = TextEditingController();
  final _messageController = TextEditingController();
  bool _isAnonymous = false;
  bool _isLoading = false;

  @override
  void dispose() {
    _amountController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  Future<void> _handlePayment() async {
    final amountText = _amountController.text.trim();
    if (amountText.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter an amount')),
      );
      return;
    }

    final amount = int.tryParse(amountText);
    if (amount == null || amount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a valid amount')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      // 1. Get Payment Intent
      // Stripe expects amount in cents for USD (e.g. 1000 = $10.00). Let's assume USD for this MVP.
      final amountInCents = amount * 100;
      final clientSecret = await StripeService.instance.createPaymentIntent(amountInCents, 'usd');

      if (clientSecret == null) {
        throw Exception('Failed to generate client secret');
      }

      // 2. Init Payment Sheet
      final isInitialized = await StripeService.instance.initPaymentSheet(clientSecret, 'Munasabat Gifts');
      if (!isInitialized) {
        throw Exception('Failed to initialize payment sheet');
      }

      // 3. Present Payment Sheet
      final isSuccess = await StripeService.instance.presentPaymentSheet();
      
      if (isSuccess) {
        // 4. Save to Firestore
        final user = ref.read(currentUserModelProvider).valueOrNull;
        if (user == null) throw Exception('Not logged in');

        final gift = GiftModel(
          id: '', // Generated by repo
          senderId: user.id,
          displayName: _isAnonymous ? null : user.name,
          amount: amount,
          currency: 'USD',
          message: _messageController.text.trim().isEmpty ? null : _messageController.text.trim(),
          isAnonymous: _isAnonymous,
          paymentStatus: 'succeeded',
          stripePaymentIntentId: clientSecret,
          createdAt: DateTime.now(),
        );

        await ref.read(giftRepositoryProvider).sendGift(widget.eventId, gift);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Gift sent successfully! Thank you!')),
          );
          context.pop();
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Payment failed: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.cream,
      appBar: AppBar(
        backgroundColor: AppColors.cream,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded, color: AppColors.brandInk),
          onPressed: () => context.pop(),
        ),
        title: Text(
          'Send a Gift',
          style: AppTextStyles.titleLarge.copyWith(color: AppColors.brandInk),
        ),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'Bless the couple with a gift',
              style: AppTextStyles.headlineMedium.copyWith(color: AppColors.brandInk),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 32),
            TextField(
              controller: _amountController,
              keyboardType: const TextInputType.numberWithOptions(decimal: false),
              decoration: InputDecoration(
                labelText: 'Amount (USD)',
                prefixIcon: const Icon(Icons.attach_money_rounded),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: const BorderSide(color: AppColors.brandInk),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: const BorderSide(color: AppColors.brandInk),
                ),
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _messageController,
              maxLines: 3,
              decoration: InputDecoration(
                labelText: 'Personal Message (Optional)',
                alignLabelWithHint: true,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: const BorderSide(color: AppColors.brandInk),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: const BorderSide(color: AppColors.brandInk),
                ),
              ),
            ),
            const SizedBox(height: 16),
            CheckboxListTile(
              value: _isAnonymous,
              onChanged: (val) {
                setState(() {
                  _isAnonymous = val ?? false;
                });
              },
              title: const Text('Send Anonymously'),
              subtitle: const Text('Your name will be hidden from the host.'),
              activeColor: AppColors.brandInk,
              contentPadding: EdgeInsets.zero,
              controlAffinity: ListTileControlAffinity.leading,
            ),
            const SizedBox(height: 32),
            _isLoading
                ? const Center(child: CircularProgressIndicator(color: AppColors.brandInk))
                : PrimaryButton(
                    label: 'Proceed to Payment',
                    onPressed: _handlePayment,
                  ),
          ],
        ),
      ),
    );
  }
}
